# Define a docker compose yaml file that initializes the server and workers
version: '3.7'

services:
  # # The master worker container
  # worker0:
  #   image: stmutasa/dtflow_test:keras
  #   network_mode: "host"
  #   environment:
  #     - NVIDIA_VISIBLE_DEVICES=all
  #   # Map the cwd to the container /dtflow_test folder
  #   volumes:
  #     - ../data:/app/data
  #   command:
  #     #["python3", "Train.py", "--worker_hosts=localhost:2223,localhost:2224", "--job_name=worker", "--task_index=0"]
  #     ["python3", "Train.py", "--worker_hosts=192.168.0.10:2223,192.168.0.5:2224", "--job_name=worker", "--task_index=0"]
  #     #["python3", "Train.py", "--worker_hosts=72.229.138.175:2223,68.174.175.23:2224", "--job_name=worker", "--task_index=0"]

  # The second worker container
  worker1:
    image: stmutasa/dtflow_test:keras
    network_mode: "host"
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - ../data:/app/data
    command:
      #["python3", "Train.py", "--worker_hosts=localhost:2223,localhost:2224", "--job_name=worker", "--task_index=1"]
      ["python3", "Train.py", "--worker_hosts=192.168.0.10:2223,192.168.0.5:2224", "--job_name=worker", "--task_index=1"]
    #["python3", "Train.py", "--worker_hosts=72.229.138.175:2223,68.174.175.23:2224", "--job_name=worker", "--task_index=1"]
